openapi: 3.0.3
info:
  title: FarmStall API
  version: v1

servers:
- url: http://farmstall.ponelat.com/v1

paths:
  /reviews:
    post:
      description: Create a new review
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: An awesome time for the whole family.
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  example: 5
      responses:
        '201':
          description: Successfully created a new Review
          content:
            application/json:
              schema:
                type: string
                properties:
                  message:
                    type: string
                    example: An awesome time for the whole family.
                  rating:
                    type: integer
                    minimum: 1
                    maximum: 5
                    example: 5
                  userId:
                    type: string
                    nullable: true
                    pattern: '^[0-9a-fA-F/-]{36}$'
                  uuid:
                    type: string
                    pattern: '^[0-9a-fA-F/-]{36}$'