openapi: 3.0.3
info:
  title: FarmStall API
  version: v1
servers:
  - url: https://farmstall.designapis.com/v1
paths: 
  /reviews:
    get:
      description: Get a bunch of reviews.
      parameters:
      - name: maxRating
        description: Filter the reviews by the maximum rating
        in: query
        schema:
          type: number
      responses:
        200:
          description: A bunch of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ ref: './schema/rating.yaml#/rating'
                properties:
                  uuid:
                    type: string
                    pattern: '^[0-9a-fA-F/-]{36}$'
                  message:
                    type: string
                  rating:
                  userId:
                    type: string
                    pattern: '^[0-9a-fA-F/-]{36}$'
                    nullable: true
                    